version: '3.7'

services:
  db:
    build: ./backend/.docker/postgres/
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=dsvendas
      - POSTGRES_PASSWORD=dsvendas
      - POSTGRES_DB=dsvendas

  pgadmin:
    image: dpage/pgadmin4
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@user.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    ports:
      - 9000:80
    depends_on:
      - db

  app:
    build: ./backend/
    ports:
      - 8080:8080
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/target
    depends_on:
      - db

  web:
    build: ./frontend/
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/usr/src/app